### ISSUE TITLE
Real Time Bus Location

### ISSUE THREAD

**Issue by RonanCodes** [appsandwich/galwaybus#1]
Do you have an endpoint for getting the real-time location of individual buses?

This guy has it in his website:
https://iecitybus.bjdodo.pw/galway/#/trips/

**Comment by appsandwich** [comment]
@RonanC Interesting. I wasn't aware that bus locations were publicly available (they're not in the API docs). I'll see if I can figure out what that site is doing to get the bus locations. Thanks!

**Comment by reideast** [comment]
@appsandwich @RonanC I've been using this web site off and on for the last week, and can posit a theory. I think the site is using the same bus time-to-arrival endpoints as you've already discovered how to utilise, but it is calculating which stop a bus is in between and places it on the route map there. While waiting for busses or riding on one, this site's map puts the bus either on or next to the nearest stop. I have not seen it show a bus moving in between stops (when there's many minutes/km between stops).

It's really quite a clever solution!

**Comment by appsandwich** [comment]
@reideast @RonanC Thanks! I initially went down that path too, but eventually found [the original project on Github](https://github.com/bjdodo/ie-city-bus), which shed some light on what's going on.

It looks like they're actually calling private Bus Eireann APIs. You can also see these being called when using the [Real Time Information feature](http://buseireann.ie/inner.php?id=403) on the Bus Eireann website.

There are three APIs that are relevant to what we'd need to get the bus locations:

- `http://buseireann.ie/inc/proto/routes.php`
- `http://buseireann.ie/inc/proto/stopPassageTdi.php`
- `http://buseireann.ie/inc/proto/vehicleTdi.php`

I prototyped a rough version that can link vehicles to their assigned routes. It still needs to be refactored and cleaned up, but I should have something soon. 👍

**Comment by appsandwich** [comment]
@reideast @RonanC Check out the [new bus APIs](https://github.com/appsandwich/galwaybus#buses). They provide basic location info for various buses and their associated routes. I still need to implement caching, so it's a little slow at the moment. If there's other info you'd like to see added to the response data, please let me know.

**Comment by RonanCodes** [comment]
Very cool, well done!

**Comment by reideast** [comment]
That's a great investigation and coding! Seriously well done

**Comment by Ryan-Gordon** [comment]
@reideast @RonanC small world !
